# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314191f0c0d9afe2311fb6ea4f62b4c2c6a0c27ac51033125db26b3492203aa3488868b3198e6b3a5cdaf81b6a31fdced6ab080779fc2232ae9beff414408743

test:
  secret_key_base: fa5695176f9564d8b4a2a81d6f55456f382a8cdd696616fd7521b28ca6a3d84cf41e066628cc1bf8065fef8907d84a4e6b3e1724a49778c68a6f6b902f48f9cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
